<div class="row flex-grow-1">
    <nav class="col-3 align-self-strech bg-light">
        <ul class="nav flex-column">
            <li class="nav-item">
                <a class="nav-link" href="./">Tableau de bord</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="add_post.php">Créer un nouvel article</a>
            </li>
        </ul>
    </nav>
    <section class="col-9">
        <header class="p-1 rounded text-center">
            <h1>Modifier l'article</h1>
        </header>
        <form action="" method="POST" class="row g-3 p-5">
            <input type="hidden" name="id_post" value="<?= intval($edit_post['id_post']); ?>">
            <div class="col-md-6">
                <label for="category" class="form-label">Catégorie de l'article</label><br>
                <?php if (!empty($errors['id_category'])) : ?>
                    <p class="text-danger bg-dark d-inline-block"><?= $errors['id_category']; ?></p>
                <?php endif; ?>
                <select id="id_category" name="id_category" class="form-select">
                    <option value="">Choisir une Catégorie</option><br>
                    <?php while ($category = $query_category->fetch()) : ?>
                        <?php if ($edit_post['id_category'] == $category['id_category']) : ?>
                            <option selected value="<?= intval($category['id_category']); ?>">
                                <?= htmlspecialchars($category['label']); ?>
                            </option>
                        <?php else : ?>
                            <option value="<?= intval($category['id_category']); ?>">
                                <?= htmlspecialchars($category['label']); ?>
                            </option>
                        <?php endif; ?>
                    <?php endwhile; ?>
                </select>
            </div>

            <div class="col-md-6">
                <label for="text" class="form-label">Auteur</label><br>
                <?php if (!empty($errors['id_user'])) : ?>
                    <p class="text-danger bg-dark d-inline-block"><?= htmlspecialchars($errors['id_user']); ?></p>
                <?php endif; ?>
                <select id="id_user" name="id_user" class="form-select">
                    <option value="">Choisir un auteur</option>
                    <?php while ($user = $query_users->fetch()) : ?>
                        <?php if ($edit_post['id_user'] == $user['id_user']) : ?>
                            <option selected value="<?= intval($user['id_user']); ?>">
                                <?= htmlspecialchars($user['pseudo']); ?>
                            </option>
                        <?php else : ?>
                            <option value="<?= intval($user['id_user']); ?>">
                                <?= htmlspecialchars($user['pseudo']); ?>
                            </option>
                        <?php endif; ?>
                    <?php endwhile; ?>
                </select>
            </div>

            <div class="col-12">
                <label for="title" class="form-label">Titre de l'article</label><br>
                <?php if (!empty($errors['title'])) : ?>
                    <p class="text-danger bg-dark d-inline-block"><?= $errors['title'] ?></p>
                <?php endif; ?>
                <?php if(!empty($edit_post['title'])) :?>
                    <input type="text" class="form-control" id="title" name="title" value="<?= htmlspecialchars($edit_post['title']); ?>">
                <?php else :?>
                    <input type="text" class="form-control" id="title" name="title" value="<?= htmlspecialchars($edit_post['title']); ?>">
                <?php endif;?>
            </div>

            <div class="col-12">
                <label for="texte" class="form-label">Texte</label><br>
                <?php if (!empty($errors['content'])) : ?>
                    <p class="text-danger bg-dark d-inline-block"><?= $errors['content'] ?></p>
                <?php endif; ?>
                <?php if(!empty($edit_post['content'])) :?>
                <textarea name="content" class="form-control" id="content" cols="30" rows="10"><?= htmlspecialchars($edit_post['content']); ?></textarea>
                <?php else :?>
                <textarea name="content" class="form-control" id="content" cols="30" rows="10"><?= htmlspecialchars($edit_post['content']); ?></textarea>
                <?php endif;?>
            </div>
            <div class="col-12">
                <button type="submit" class="btn btn-primary">Enregistrer</button>
            </div>
        </form>

    </section>
</div>