<div class="container-lg mx-auto p-4">
    <header class="bg-light mb-4 p-1 rounded text-center">
        <h1>Acceuil du blog</h1>
        <p>Les derniers articles postés</p>
    </header>

    <div class="row justify-content-center mx-auto">

        <?php while ($post = $query->fetch()) : ?>
            <div class="col-sm-3 p-0 m-3 card shadow">
                <div class="card-header bg-warning">
                    <h2 class="card-title text-light h5"><?= htmlspecialchars($post['title']); ?></h2>
                    <p class="card-text text-dark">
                        Dans la catégorie: <span class="badge bg-dark"><?= htmlspecialchars($post['label']); ?></span></p>
                </div>
                <div class="card-body">
                    <p class="card-text"><?= htmlspecialchars($post['content']); ?></p>
                    <div class="text-end">
                        <a href="post.php?id=<?= intval($post['id_post']) ?>" class="btn btn-warning">Lire la suite</a>
                    </div>
                </div>
                <div class="card-footer bg-secondary">
                    <p class="text-light"><strong><?= htmlspecialchars($post['pseudo']); ?></strong><?= ' le ' . htmlspecialchars($post['date']); ?></p>
                </div>
            </div>
        <?php endwhile; ?>
    </div>
    <nav class="mt-5" aria-label="Page navigation example">
        <ul class="pagination justify-content-center">
            <li class="page-item"><a class="page-link link-dark" href="#">Previous</a></li>
            <li class="page-item"><a class="page-link link-dark" href="#">1</a></li>
            <li class="page-item"><a class="page-link link-dark" href="#">Next</a></li>
        </ul>
    </nav>
</div>