<section class="m-auto p-4">
    <h1 class="text-center">Se connecter sur le site</h1>
    <?php if (isset($error)) : ?>
        <p class="text-danger"><?= $error; ?></p>
    <?php endif; ?>
    <form action="login.php" method="POST">
        <div class="mb-3">
            <label for="email" class="form-label">Adresse Email</label>
            <input type="text" class="form-control" name="email" id="email">
        </div>
        <div class="mb-3">
            <label for="exampleInputPassword1" class="form-label">Mot de passe</label>
            <input type="password" class="form-control" name="pass" id="pass">
        </div>
        <!--
                <div class="mb-3 form-check">
                    <input type="checkbox" class="form-check-input" id="exampleCheck1">
                    <label class="form-check-label" for="exampleCheck1">Se souvenir de moi</label>
                </div>-->
        <div class="text-end">
            <button type="submit" class="btn btn-primary">Se connecter</button>
        </div>
    </form>
    <div class="text-center mt-5">Vous n'avez pas de compte <a href="register">Créer</a> votre compte</div>
</section>