<div class="admin-container">
    <nav class="admin-nav">
        <ul>
            <li><a href="admin.php">Gestion des demandes de devis</a></li>
            <hr>
            <li><a href="management_users.php">Gestion des comptes</a></li>
            <hr>
            <li><a href="subject.php">Gestion des sujets</a></li>
        </ul>
    </nav>
    <section class="admin-section">
        <header class="admin-header">
            <h1>Tableau de bord</h1>
        </header>

        <!-- Tu peux le déplacer où ça t'arranges -->
        <div class="filter-container">
            <p>Filtres :</p>
            <nav class="filter-nav">
                <a class="filter-link" data-filter="all">Tous les devis</a>
                <hr>
                <a class="filter-link" data-filter="A+traiter">Devis à traiter</a>
                <hr>
                <a class="filter-link" data-filter="En+cours">Devis en cours de traitement</a>
                <hr>
                <a class="filter-link" data-filter="Traité">Devis traités</a>
            </nav>

        </div>

        <table class="admin-table">
            <caption>Liste des demandes de devis</caption>
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Nom</th>
                    <th>Prénom</th>
                    <th>Email</th>
                    <th>Numéro de téléphone</th>
                    <th>Ville</th>
                    <th>Sujet</th>
                    <th>Date</th>
                    <th>Etat</th>
                    <th>Examiner</th>
                    <th>Supprimer</th>
                </tr>
            </thead>
            <tbody>
                <?php while ($devis = $query_devis->fetch()) : ?>
                    <tr>
                        <td><?= intval($devis['id_devis']); ?></td>
                        <td><?= htmlspecialchars($devis['lastname']) ?></td>
                        <td><?= htmlspecialchars($devis['firstname']) ?></td>
                        <td><?= htmlspecialchars($devis['email']) ?></td>
                        <td><?= htmlspecialchars($devis['tel']) ?></td>
                        <td><?= htmlspecialchars($devis['city']) ?></td>
                        <td><?= htmlspecialchars($devis['subject']) ?></td>
                        <td><?= htmlspecialchars($devis['date']) ?></td>
                        <td><?= htmlspecialchars($devis['status']) ?></td>
                        <td>
                            <a class="table-btn" href="display_devis.php?id=<?= intval($devis['id_devis']) ?>" title="Modifier l'utilisateur">
                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi-sliders" viewBox="0 0 16 16">
                                    <path fill-rule="evenodd" d="M11.5 2a1.5 1.5 0 1 0 0 3 1.5 1.5 0 0 0 0-3zM9.05 3a2.5 2.5 0 0 1 4.9 0H16v1h-2.05a2.5 2.5 0 0 1-4.9 0H0V3h9.05zM4.5 7a1.5 1.5 0 1 0 0 3 1.5 1.5 0 0 0 0-3zM2.05 8a2.5 2.5 0 0 1 4.9 0H16v1H6.95a2.5 2.5 0 0 1-4.9 0H0V8h2.05zm9.45 4a1.5 1.5 0 1 0 0 3 1.5 1.5 0 0 0 0-3zm-2.45 1a2.5 2.5 0 0 1 4.9 0H16v1h-2.05a2.5 2.5 0 0 1-4.9 0H0v-1h9.05z" />
                                </svg>
                            </a>
                        </td>
                        <td>
                            <a class="table-btn confirmDelete" href="delet_devis.php?id=<?= intval($devis['id_devis']) ?>" title="Supprimer l'utilisateur">
                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi-x-square" viewBox="0 0 16 16">
                                    <path d="M14 1a1 1 0 0 1 1 1v12a1 1 0 0 1-1 1H2a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1h12zM2 0a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2H2z" />
                                    <path d="M4.646 4.646a.5.5 0 0 1 .708 0L8 7.293l2.646-2.647a.5.5 0 0 1 .708.708L8.707 8l2.647 2.646a.5.5 0 0 1-.708.708L8 8.707l-2.646 2.647a.5.5 0 0 1-.708-.708L7.293 8 4.646 5.354a.5.5 0 0 1 0-.708z" />
                                </svg>
                            </a>
                        </td>
                    </tr>
                <?php endwhile; ?>
            </tbody>
        </table>

        <div class="admin-pagination">
            <div>
                <form class="nb-devis" action="" method="GET">
                    <label for="nb_devis" class="admin-label">Nombre de devis par page</label>
                    <select name="nb_devis" id="nb_devis" required class="admin-select">
                        <?php if (!empty($_GET) && isset($_GET['nb_devis']) && ($_GET['nb_devis'] > 0) && ($_GET['nb_devis'] <= 15)) : ?>
                            <option><?= intval($_GET['nb_devis']); ?></option>
                        <?php endif; ?>
                        <optgroup label="Choisir le nombre de demandes">
                            <option value="5">5</option>
                            <option value="10">10</option>
                            <option value="15">15</option>
                        </optgroup>
                    </select>
                    <input class="admin-input" type="submit" value="Valider">
                </form>
            </div>

            <nav class="nav-pagination">
                <ul class="pagination-nav">
                    <li>
                        <?php if ($currentPage == 1) : ?>   
                            <p>Précédent</p>
                        <?php else : ?>
                            <?php if (!empty($_GET) && isset($_GET['nb_devis']) && ($_GET['nb_devis'] > 0) && ($_GET['nb_devis'] <= 15)) : ?>
                                <a href="./admin.php?page=<?= ($currentPage - 1) ?>&nb_devis=<?= intval($_GET['nb_devis']); ?>">Précédent</a>
                            <?php else : ?>
                                <a href="./admin.php?page=<?= ($currentPage - 1) ?>">Précédent</a>
                            <?php endif; ?>
                        <?php endif; ?>
                    </li>
                    <?php for ($page = 1; $page <= $nb_page; $page++) : ?>
                        <li>
                            <?php if (!empty($_GET) && isset($_GET['nb_devis']) && ($_GET['nb_devis'] > 0) && ($_GET['nb_devis'] <= 15)) : ?>
                                <a href="./admin.php?page=<?= $page ?>&nb_devis=<?= intval($_GET['nb_devis']); ?>" class="<?= ($currentPage == $page) ? "active" : "" ?>"><?= $page ?></a>
                            <?php else : ?>
                                <a href="./admin.php?page=<?= $page ?>" class="<?= ($currentPage == $page) ? "active" : "" ?>"><?= $page ?></a>
                            <?php endif; ?>
                        </li>
                    <?php endfor; ?>
                    <li>
                        <?php if ($currentPage == $nb_page) : ?>
                            <p>Suivant</p>
                        <?php else : ?>
                            <?php if (!empty($_GET) && isset($_GET['nb_devis']) && ($_GET['nb_devis'] > 0) && ($_GET['nb_devis'] <= 15)) : ?>
                                <a href="./admin.php?page=<?= ($currentPage + 1) ?>&nb_devis=<?= intval($_GET['nb_devis']); ?>">Suivant</a>
                            <?php else : ?>
                                <a href="./admin.php?page=<?= ($currentPage + 1) ?>">Suivant</a>
                            <?php endif; ?>
                        <?php endif; ?>
                    </li>
                </ul>
            </nav>
        </div>
    </section>
</div>

<?php /*   */ ?>
<script>
    let links = document.querySelectorAll('.filter-link');

    links.forEach(link => {
        
        link.addEventListener('click', function(){
            let filter = this.getAttribute('data-filter');
    
            let url = './admin.php?filter=' + filter;

            console.log(url);

            ajaxGet(url, function (response){
                let estimate = JSON.parse(response);
                console.log(estimate);
            })


        })
    });
    

    function ajaxGet(url, callback) {
			
			const req = new XMLHttpRequest();
			
			req.open("GET", url, true);
			
			req.addEventListener('load', function () {
				if (req.status >= 200 && req.status < 400) {
					callback(req.response);
				} else {
					console.error(req.status + " " + req.statusText + " " + url);
				}
			});
			
			req.addEventListener('error', function () {
				console.error('Erreur réseau avec l\'url :' + url);
			});
			
			//fin de la transaction GET
			req.send(null);
		}

</script>