<div>
    <p>Prénom : <?= $aDevis['firstname']; ?></p>
</div>

<div>
    <p>Nom : <?= $aDevis['lastname']; ?></p>
</div>

<div>
    <p>Adresse mail : <?= $aDevis['email']; ?></p>
</div>

<div>
    <p>Numéro de téléphone : <?= $aDevis['tel']; ?></p>
</div>

<div>
    <p>Ville : <?= $aDevis['city']; ?></p>
</div>

<div>
    <p>Sujet : <?= $aDevis['subject']; ?></p>
</div>

<div>
    <p>Message : <?= $aDevis['message']; ?></p>
</div>

<div>
    <p>Date : <?= $aDevis['date']; ?></p>
</div>
<div>
    <form action="" method="POST">
        <div>
            <label for="status">Sujet</label>
            <select name="status" id="status" required>
                <option value="<?= $aDevis['status']; ?>"><?= $aDevis['status']; ?></option>
                <optgroup label="Choisir l'état du devis">
                    <option value="En cours">En cours</option>
                    <option value="Traité">Traité</option>
                    <option value="A traiter">A traiter</option>
                </optgroup>
                
            </select>
        </div>

        <div>
            <input type="submit" value="Valider">
            <input type="reset" value="Annuler">
        </div>
    </form>

</div>