<div>
    <nav>
        <ul>
            <li><a id="test" href="#" aria-id="SFEESFESEFSEFSEFSFESZQZDQZQZZQSDZQSDQZSDQZSD">Gestion des comptes</a></li>
            <hr>
        </ul>
    </nav>
    <section>
        <header>
            <h1>Modification du compte utilisateur</h1>
        </header>
        <form method="POST" action="">
            <input type="hidden" name="id_user" value="<?= intval($aUser['id_user']); ?>">
            <label for="text">Choix du niveau de permissions</label>
            <select name="id_permission" id="id_permission">
                <?php while ($permission = $query_permissions->fetch()) : ?>
                    <?php if ($permission['id_permission'] == $aUser['id_permission']) : ?>
                        <option selected value="<?= intval($permission['id_permission']); ?>"><?=htmlspecialchars($permission['permission']); ?></option>
                    <?php else : ?>
                        <option value="<?= intval($permission['id_permission']); ?>"><?= htmlspecialchars($permission['permission']); ?></option>
                    <?php endif; ?>
                <?php endwhile; ?>
            </select>
            <div>
                <input type="submit" value="Valider">
                <input type="reset" value="Annuler">
            </div>
        </form>
    </section>
</div>
</section>
</div>