<section class="devis">
	<a href="estimate.php" class="devis-btn">Demande de devis</a>
</section>

<section class="presentation">
	<p class="presentation-title">Bienvenue chez E.C.T.B Service</p>
	<p><strong>Mickael Griffith</strong> fondateur et président.</p>
	<p>Travail depuis plus de 5 ans dans le domaine de l’électricité et de la climatisation.</p>
	<p>Il possède un BEP, un bac pro électrotech ainsi qu’une attestation d’aptitude dans la climatisation.</p>
	<h3 class="pres-title"><span class="first-letter">N</span><strong>ous travaillons avec :</strong></h3>
	<div class="workwith">
		<img class="sonepar marques-img" src="./img/Sonepar_logo.png" alt="sonepar connect">
		<img class="cd-sud marques-img" src="./img/cdsud_logo.png" alt="cd sud">
		<img class="atlantic marques-img" src="./img/atlantic_logo.png" alt="atlantic">
		<img class="mitsubishi marques-img" src="./img/MitsubishiElectric_logo.png" alt="mitsubishi electric">
		<img class="daikin marques-img" src="./img/DAIKIN_logo.png" alt="daikin">
		<img class="legrand marques-img" src="./img/Legrand_logo.png" alt="legrand">
		<img class="haier marques-img" src="./img/haier_logo.png" alt="haier">
	</div>
	<hr class="hr">
	<h3 class="pres-title"><span class="first-letter">N</span><strong>os engagements :</strong></h3>
	<ul class="ul-engagement">
		<li class="liste-engagement">Respect de l’environnement</li>
		<li class="liste-engagement">Proximité</li>
		<li class="liste-engagement">Qualité</li>
		<li class="liste-engagement">Efficacité</li>
		<li class="liste-engagement">Rapidité</li>
	</ul>
</section>

<hr class="hr">

<section class="realisations">
	<h3 class="pres-title"><span class="first-letter">Q</span><strong>uelques exemples de réalisations</strong></h3>
	<div class="real">
		<img class="real1 real-img" src="./img/real1.jpeg" alt="exemple réalisation">
		<img class="real2 real-img" src="./img/real2.jpeg" alt="exemple réalisation">
		<img class="real3 real-img" src="./img/real3.jpg" alt="exemple réalisation">
		<img class="real4 real-img" src="./img/real4.jpg" alt="exemple réalisation">
		<img class="real5 real-img" src="./img/real5.jpg" alt="exemple réalisation">
		<img class="real6 real-img" src="./img/real6.jpg" alt="exemple réalisation">
		<img class="real7 real-img" src="./img/real7.jpg" alt="exemple réalisation">
		<img class="real8 real-img" src="./img/real8.jpg" alt="exemple réalisation">
	</div>
</section>


<hr class="hr">

<section class="devis2">
	<h3 class="pres-title"><span class="first-letter">C</span><strong>onvaincu ?</strong></h3>
	<a href="estimate.php" class="devis-btn-2">Demander un devis</a>
</section>

<section class="localisation">
	<iframe src="https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d11547.827936232625!2d5.0877498!3d43.6490633!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0xb56097c95533963a!2sECTB%20SERVICE!5e0!3m2!1sfr!2sfr!4v1620083438049!5m2!1sfr!2sfr" width="100%" height="400" style="border:0;" allowfullscreen="" loading="lazy"></iframe>
</section>