<section>
    <div class="devis-form">
        <form method="POST" action="">
            <fieldset>
                <legend class="form-legend">Créer un compte</legend>
                <div class="div-label-input">
                    <label for="text">Prénom</label>
                    <?php if (isset($aErrors['firstname'])) : ?>
                        <p class="error"><?= htmlspecialchars($aErrors['firstname']); ?></p>
                    <?php endif; ?>
                    <input type="text" placeholder="Prénom" name="firstname" id="firstname" value="<?= htmlspecialchars($aUserInfos['firstname'])?>">
                </div>
                <div class="div-label-input">
                    <label for="text">Nom</label>
                    <?php if (isset($aErrors['lastname'])) : ?>
                        <p class="error"><?= htmlspecialchars($aErrors['lastname']); ?></p>
                    <?php endif; ?>
                    <input type="text" placeholder="Nom" name="lastname" id="lastname" value="<?= htmlspecialchars($aUserInfos['lastname'])?>">
                </div>
                <div class="div-label-input">
                    <label for="text">Adresse mail</label>
                    <?php if (isset($aErrors['email'])) : ?>
                        <p class="error"><?= htmlspecialchars($aErrors['email']); ?></p>
                    <?php endif; ?>
                    <input type="email" require placeholder="Adresse email valide" name="email" id="email" value="<?= htmlspecialchars($aUserInfos['email'])?>">
                </div>
                <div class="div-label-input">
                    <label for="text">Pseudo</label>
                    <?php if (isset($aErrors['pseudo'])) : ?>
                        <p class="error"><?= htmlspecialchars($aErrors['pseudo']); ?></p>
                    <?php endif; ?>
                    <input type="text" placeholder="Nom public sur le site" name="pseudo" id="pseudo" value="<?= htmlspecialchars($aUserInfos['pseudo'])?>">
                </div>
                <div class="div-label-input">
                    <label for="text">Mot de passe</label>
                    <?php if (isset($aErrors['passwordFormat'])) : ?>
                        <p class="error">Votre mot de passe doit contenir au moins :</p>
                        <p class="error">8 caractères, Une majuscule, Une miniscule, Un chiffre</p>
                    <?php endif; ?>
                    <?php if (isset($aErrors['password'])) : ?>
                        <p class="error"><?= htmlspecialchars($aErrors['password']); ?></p>
                    <?php endif; ?>
                    <input type="password" placeholder="Choisir un mot de passe" name="password" id="password">
                    <br>
                    <input type="checkbox" id="displayPassword">
                    <label id="checkbox" for="text">Afficher le mot de passe</label>
                </div>
                <div class="div-label-input">
                    <label for="text">Confirmation mot de passe</label>
                    <?php if (isset($aErrors['confirmedPassword'])) : ?>
                        <p class="error"><?= htmlspecialchars($aErrors['confirmedPassword']); ?></p>
                    <?php endif; ?>
                    <input type="password" placeholder="Confirmation du mot de passe" name="confirmedPassword" id="confirmedPassword">
                </div>
                <div>
                    <button class="devis-btn-3" type="submit">Valider</button>
                    <button class="devis-btn-3" type="reset">Annuler</button>
                </div>
            </fieldset>
        </form>
    </div>
</section>