<div class="subject-container">
	<nav class="subject-nav">
		<ul>
			<li><a href="management_users.php">Gestion des comptes</a></li>
			<hr>
			<li><a href="admin.php">Gestion des demandes de devis</a></li>
			<hr>
			<li><a href="subject.php">Gestion des sujets</a></li>
		</ul>
	</nav>

	<section class="subject-section">
		<header class="subject-header">
			<h1>Sujets de devis</h1>
		</header>

		<table class="admin-table">
			<caption>Liste des sujets de devis</caption>
			<thead>
				<tr>
					<th>Label</th>
					<th>Modifier</th>
					<th>Supprimer</th>
				</tr>
			</thead>
			<tbody>
				<?php foreach ($subjects as $subject) : ?>
					<tr>
						<td><?= $subject['label_subject'] ?></td>
						<td>
							<a class="table-btn modifySubject" data-subject="<?= $subject['label_subject'] ?>" title="Modifier le sujet">
								<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi-sliders" viewBox="0 0 16 16">
									<path fill-rule="evenodd" d="M11.5 2a1.5 1.5 0 1 0 0 3 1.5 1.5 0 0 0 0-3zM9.05 3a2.5 2.5 0 0 1 4.9 0H16v1h-2.05a2.5 2.5 0 0 1-4.9 0H0V3h9.05zM4.5 7a1.5 1.5 0 1 0 0 3 1.5 1.5 0 0 0 0-3zM2.05 8a2.5 2.5 0 0 1 4.9 0H16v1H6.95a2.5 2.5 0 0 1-4.9 0H0V8h2.05zm9.45 4a1.5 1.5 0 1 0 0 3 1.5 1.5 0 0 0 0-3zm-2.45 1a2.5 2.5 0 0 1 4.9 0H16v1h-2.05a2.5 2.5 0 0 1-4.9 0H0v-1h9.05z" />
								</svg>
							</a>
						</td>
						<td>
							<a class="table-btn confirmDelete" href="delete_subject.php?id=<?= intval($subject['id_subject']) ?>" title="Supprimer le sujet">
								<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi-x-square" viewBox="0 0 16 16">
									<path d="M14 1a1 1 0 0 1 1 1v12a1 1 0 0 1-1 1H2a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1h12zM2 0a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2H2z" />
									<path d="M4.646 4.646a.5.5 0 0 1 .708 0L8 7.293l2.646-2.647a.5.5 0 0 1 .708.708L8.707 8l2.647 2.646a.5.5 0 0 1-.708.708L8 8.707l-2.646 2.647a.5.5 0 0 1-.708-.708L7.293 8 4.646 5.354a.5.5 0 0 1 0-.708z" />
								</svg>
							</a>
						</td>
					</tr>
				<?php endforeach ?>
			</tbody>
		</table>
	</section>
</div>